apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: metatheory/frontend:2022-12-03-15-23-37
          name: frontend
          ports:
            - containerPort: 80
              name: frontend-port
              protocol: TCP
          imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: frontend-port
  selector:
    app: frontend
