const BASE_URL_PRODUCTS = process.env.VUE_APP_URL_PRODUCTS
const BASE_URL_CART = process.env.VUE_APP_URL_CART
const BASE_URL_STORE = process.env.VUE_APP_URL_STORE
const BASE_URL_NOTIF = process.env.VUE_APP_URL_NOTIF

export {
    BASE_URL_CART,
    BASE_URL_NOTIF,
    BASE_URL_STORE,
    BASE_URL_PRODUCTS
}